---
# Setup kubernetes
- name: Install LAMP stack
  hosts: test
  tasks:
    - name: Disable swap
      become: yes
      command: echo "cgroup_enable=memory cgroup_memory=1" >> "/boot/firmware/cmdline.txt"

    - name: Install snapd
      become: yes
      apt:
        name: snapd
        state: present
        update_cache: yes

    - name: Install microk8s
      become: yes
      snap:
        name: microk8s
        classic: yes

