---
# Setup kubernetes
- name: Install microk8s
  hosts: kubernetes
  tasks:
    - name: Disable swap
      become: yes
      command: echo "cgroup_enable=memory cgroup_memory=1" >> "/boot/firmware/cmdline.txt"

    - name: Install snapd
      become: yes
      apt:
        name: snapd
        state: present
        update_cache: yes

    - name: Install Kernal modules
      become: yes
      apt:
        name: linux-modules-extra-raspi
        state: present
        update_cache: yes

    - name: Install microk8s
      become: yes
      snap:
        name: microk8s
        classic: yes
        channel: 1.25
